### ISSUE TITLE
Plotting bug on geom_hdr_lines_fun?

### ISSUE THREAD

**Issue by afranks86** [jamesotto852/ggdensity#20]
I tried plotting the following mixture density using `geom_hdr_lines_fun`:

```
mixture_density <- function(x, y) {
  (1/2*dnorm(x, -2) + 1/2*dnorm(x, 2)) * dnorm(y, sd=2)
}

ggplot() + ggdensity::geom_hdr_lines_fun(fun=mixture_density, xlim=c(-8, 8), ylim=c(-8, 8)) + theme_bw()
```
I got this weird line cutting across the two modes of the contours.  

<img width="599" alt="Screen Shot 2022-08-23 at 7 10 02 PM" src="https://user-images.githubusercontent.com/8409176/186302390-69e2bcaa-0925-4be1-a355-281b10364dc7.png">

**Comment by jamesotto852** [comment]
Thanks for catching this! `StatHdrFunLines` was using `iso_to_polygon()` when it should have been using `iso_to_path()`. Fixed in https://github.com/jamesotto852/ggdensity/commit/1cc1fcf27702c4ae93dd637bba0111c95f27499a.

``` r
library("ggdensity")
#> Loading required package: ggplot2

mixture_density <- function(x, y) {
  (1/2*dnorm(x, -2) + 1/2*dnorm(x, 2)) * dnorm(y, sd = 2)
}

ggplot() + 
  geom_hdr_lines_fun(fun = mixture_density, xlim = c(-8, 8), ylim = c(-8, 8)) +
  theme_bw()
```

![](https://i.imgur.com/UtkPskH.png)

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
